CREATE TABLE cards (
    id SERIAL PRIMARY KEY,
    registration_number VARCHAR(50) NOT NULL, -- Регистрационный номер (unique identifier generated by system)
    creation_date TIMESTAMP NOT NULL,         -- Дата создания документа
    region VARCHAR(50) NOT NULL,              -- Регион
    basic_info_id INT REFERENCES basic_info(id),
    case_details_id INT REFERENCES case_details(id),
    person_details_id INT REFERENCES person_details(id),
    investigation_details_id INT REFERENCES investigation_details(id),
    organizer_details_id INT REFERENCES organizer_details(id),
    business_details_id INT REFERENCES business_details(id),
    defender_details_id INT REFERENCES defender_details(id)
);
CREATE TABLE basic_info (
    id SERIAL PRIMARY KEY,
    registration_number VARCHAR(50) UNIQUE NOT NULL, -- Unique registration number
    creation_date TIMESTAMP NOT NULL,                -- Document creation date
    region VARCHAR(50) NOT NULL                      -- Region information
);

CREATE TABLE case_details (
    id SERIAL PRIMARY KEY,
    case_number VARCHAR(15) NOT NULL CHECK (LENGTH(case_number) = 15), -- Номер дела, 15-digit format
    registration_date TIMESTAMP NOT NULL,          -- Дата регистрации дела
    criminal_code_article VARCHAR(50),             -- Статья УК
    case_decision TEXT,                            -- Решение по делу
    case_summary TEXT,                             -- "Краткая фабула(чтобы это не значило)"
    relation_to_event TEXT                         -- Отношение вызываемого к событию и субьекту
);

CREATE TABLE person_details (
    id SERIAL PRIMARY KEY,
    invited_person_iin VARCHAR(12) NOT NULL CHECK (LENGTH(invited_person_iin) = 12), -- ИИН, 12 digits
    invited_person_full_name VARCHAR(255),    -- ФИО приглашенного
    invited_person_position VARCHAR(100),     -- Позиция
    organization_bin_or_iin VARCHAR(12) NOT NULL CHECK (LENGTH(organization_bin_or_iin) = 12), -- Организации BIN/IIN
    workplace VARCHAR(255),                   -- Место работы
    invited_person_status VARCHAR(50)         -- Статус приглашенного
);
CREATE TABLE investigation_details (
    id SERIAL PRIMARY KEY,
    planned_investigative_actions TEXT NOT NULL, -- Планируемые следственные действия (обязательное поле, ручнойввод);
    scheduled_date_time TIMESTAMP NOT NULL,      -- Дата и время проведения (календарный и временной выбор);
    location VARCHAR(255),                       -- Место проведения (справочник);
    type_of_investigation VARCHAR(50),           -- Виды планируемого следствия (справочник);
    expected_outcome TEXT                        -- Результат от планируемого следственного действия (обязательное поле, ручной ввод).
);

CREATE TABLE organizer_details (
    id SERIAL PRIMARY KEY,
    investigator VARCHAR(255) NOT NULL  -- Следователь (автоподтягивание с личного кабинета);
);
CREATE TABLE business_details (
    id SERIAL PRIMARY KEY,
    is_business_related BOOLEAN NOT NULL,                  -- Относится ли к бизнесу (справочник);
    pension_bin_or_iin VARCHAR(12) CHECK (LENGTH(pension_bin_or_iin) = 12), -- Пенсионные BIN/IIN
    pension_workplace VARCHAR(255),                        -- Место работы (пенсионные отчисления) (автоподтягивание последнего места работы с базы пенсионных отчислений по ИИН вызываемого, отображается пользователю с ролью Аналитик СД);
    entrepreneur_participation TEXT                        -- Обоснование и необходимость участия предпринимателя (обязательное поле, ручной ввод);
);

CREATE TABLE defender_details (
    id SERIAL PRIMARY KEY,
    defender_iin VARCHAR(12) CHECK (LENGTH(defender_iin) = 12), -- ИИН защитника (ручной ввод, ФЛК 12 цифр);
    defender_full_name VARCHAR(255)                             -- ФИО защитника (автоподтягивание по ИИН защитника);
);
