CREATE TABLE cards (
    id SERIAL PRIMARY KEY,
    registration_number VARCHAR(50) NOT NULL, -- Регистрационный номер (unique identifier generated by system)
    creation_date TIMESTAMP NOT NULL,         -- Дата создания документа
    region VARCHAR(50) NOT NULL,              -- Регион
    basic_info_id INT REFERENCES basic_info(id),
    case_details_id INT REFERENCES case_details(id),
    person_details_id INT REFERENCES person_details(id),
    investigation_details_id INT REFERENCES investigation_details(id),
    organizer_details_id INT REFERENCES organizer_details(id),
    business_details_id INT REFERENCES business_details(id),
    defender_details_id INT REFERENCES defender_details(id),
    version integer NOT NULL DEFAULT 1
);